### ISSUE TITLE
I get silently disconnect if I try to add subscribe to a remoteci

### ISSUE THREAD

**Issue by goneri** [redhat-cip/dci-ui#48] opened 2018-01-04 18:50 UTC
I'm in the OpenStack team, switch is one level below the goneri team. I want to subscribe to my remoteci. So I go on https://www.distributed-ci.io/notification and click on the ⊞ signe.

The following URL is called:
`https://api.distributed-ci.io/api/v1/remotecis/af991b96-bfe0-4e00-bd87-5c98893c3238/users`
The payload sent by the browser:
```
{"user_id":"51bd34bf-5767-48c2-aeae-b49212480533"}
```

answer:
```
{
  "message": "Operation not authorized.",
  "payload": {},
  "status_code": 401
}
```

If I retry to do the same, I get a different result:
```
{
  "message": "Authorization header malformed",
  "payload": {},
  "status_code": 401
}
```
I actually disconnected. I reload the browser and get redirected to auth page.

**Comment by guillaumevincent** [comment] 2018-01-05 12:44
Hello @Goneri,
I think the issue is in dci-control-server not allowing to subscribe to remoteci notification if the user do not belong to the remoteci.

**Comment by guillaumevincent** [comment] 2018-02-06 09:45
It will be fix on the control server with the recent update on remoteci subscription

**Comment by goneri** [comment] 2018-02-06 18:31
Thanks @guillaumevincent! I reopen because I would prefer to close the issue the day the issue is effectively fixed.

**Comment by guillaumevincent** [comment] 2018-02-13 15:02
fixed in production

**Closed as completed by guillaumevincent** 2018-02-13 15:02 UTC
Labels: bug

**Comment by goneri** [comment] 2018-02-13 16:08
Nice, thanks @guillaumevincent
